version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - REPOSITORY_URI=466045224920.dkr.ecr.us-east-1.amazonaws.com/chefomardee

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t whit .
      - docker tag whit public.ecr.aws/g8f8p7n1/chefomardee:whit
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/g8f8p7n1/chefomardee:whit
      - printf '[{"name":"whit","imageUri":"%s"}]' public.es/g8f8p7n1/chefomardee:whit > imagedefinitions.json
      - echo Writing image definitions file...
artifacts:
  files: imagedefinitions.json











# WORKING CODE
#vVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11.2
#   pre_build:
#     commands:
#       - python -m py_compile main.py
#       - echo Nothing to do in the pre_build phase...
#   build:
#     commands:
#       - echo Build started on `date`
#   post_build:
#     commands:
#       - echo Build completed on `date`
