version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.2
  pre_build:
    commands:
      - COMMIT_HASH=$(python3 main.py)
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
