version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.2
  pre_build:
    commands:
      - python -m py_compile main.py
      - export DOCKER_VERSION="20.10.7"
      - DOCKER_BUCKET="download.docker.com"
      - DOCKER_CHANNEL="stable"
      - DOCKER_SHA256="34ad50146fce29b28e5115a1e8510dd5232459c9a4a9f28f65909f92cca314d9"
      - curl -fSL "https://${DOCKER_BUCKET}/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz
      - echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c -
      - tar --extract --file docker.tgz --strip-components 1  --directory /usr/local/bin/
      - rm docker.tgz
      - docker -v
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g8f8p7n1
      - REPOSITORY_URI=public.ecr.aws/g8f8p7n1/chefomardee
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=whi
      - echo Nothing to do in the pre_build phrase...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t whi .
      - docker tag whi $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push public.ecr.aws/g8f8p7n1/chefomardee:whi
      - echo Build completed on `date`
