version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.2
  pre_build:
    commands:
      - python -m py_compile main.py
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 466045224920.dkr.ecr.us-east-1.amazonaws.com      
      - REPOSITORY_URI=public.ecr.aws/g8f8p7n1/chefomardee
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=whi
      - echo Nothing to do in the pre_build phrase...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t whi .
      - docker tag whi $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push public.ecr.aws/g8f8p7n1/chefomardee:whi
      - echo Build completed on `date`
